name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

     # Install npm packages and firebase
      - name: Install npm packages
        run: |
          cd public
          npm install
          npm audit fix
          npm install firebase-tools
          
      # Run tests
      - name: Run tests
        run: |
          cd functions
          npm run test
          
      # Deploying the functions to firebase
      - name: Deploy to Firebase
        run: |
          cd functions
          npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

